server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Drive
          uri: http://localhost:8081
          predicates:
            - Path=/files/**, 
        - id: Collaboration
          uri: http://localhost:8082
          predicates:
            - Path=/documents/**, 
        - id: Video Processing
          uri: http://localhost:8083
          predicates:
            - Path=/videos/**, 
        - id: User Management
          uri: http://localhost:8084
          predicates:
            - Path=/users/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Drive
          uri: http://drive:8080
          predicates:
            - Path=/files/**, 
        - id: Collaboration
          uri: http://collaboration:8080
          predicates:
            - Path=/documents/**, 
        - id: Video Processing
          uri: http://videoProcessing:8080
          predicates:
            - Path=/videos/**, 
        - id: User Management
          uri: http://userManagement:8080
          predicates:
            - Path=/users/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
