---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Drive
  labels:
    app: Drive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Drive
  template:
    metadata:
      labels:
        app: Drive
    spec:
      containers:
        - name: Drive
          image: username/Drive:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Collaboration
  labels:
    app: Collaboration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Collaboration
  template:
    metadata:
      labels:
        app: Collaboration
    spec:
      containers:
        - name: Collaboration
          image: username/Collaboration:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Video Processing
  labels:
    app: Video Processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Video Processing
  template:
    metadata:
      labels:
        app: Video Processing
    spec:
      containers:
        - name: Video Processing
          image: username/Video Processing:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: User Management
  labels:
    app: User Management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: User Management
  template:
    metadata:
      labels:
        app: User Management
    spec:
      containers:
        - name: User Management
          image: username/User Management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Drive
  labels:
    app: Drive
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Drive


---


apiVersion: v1
kind: Service
metadata:
  name: Collaboration
  labels:
    app: Collaboration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Collaboration


---


apiVersion: v1
kind: Service
metadata:
  name: Video Processing
  labels:
    app: Video Processing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Video Processing


---


apiVersion: v1
kind: Service
metadata:
  name: User Management
  labels:
    app: User Management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: User Management

